#ifndef VARIABLE_local_HEADER
#define VARIABLE_local_HEADER


#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <time.h>
#include <iostream>
#include <fstream>
#include <math.h>
#include <vector>
#include <set>
#include <string>
#include <sstream>
#include <errno.h>
#include <cstring>
#include <cstdlib>
#include <mutex>

using namespace std;

#include <cplex.h>

#include "graph/algorithms/graph_gen.h"
#include "graph/algorithms/decode.h"
#include "utils/utils.h"
#include "clique/clique_sat.h"
#include "clique/clique_clisat.h"
#include "clique/interdiction/ramsey.h"
#include "graph/algorithms/graph_func.h"
#include "clique/clique_config.h"
#include <utility>
#include <vector>


struct object
{
	int item;
	double score;
};

/***********************************************************************************/
// Structure to store a cut line (a series of numbers)
/***********************************************************************************/
struct cut_line
{
	int num_elements;     // how many numbers are in the line
	int* values;          // the values read from the line
	int clique_num_elements;
	int* clique_values;
};

/***********************************************************************************/
// Structure to store all cuts read from a file
/***********************************************************************************/
struct cut_data
{
	int num_lines;        // how many lines there are
	cut_line* lines;      // array of lines
	bool loaded;          // flag to know if cuts have been loaded
	bool has_clique_data; // rows include generating clique data after '|'
};

typedef class data
{

public:

	/////////////////////////////////////INPUT/////////////////////////////////////
	int   PARAM_SIZE_GRAPH;
	int   PARAM_M;
	int   PARAM_N;
	int   PARAM_ALGO;//1 for the feasibility model and 2 the generalized mode algo 3 quaglie
	int   PARAM_OPTIONS;//with ALGO 2, set it to 1 to impose theta <= m -1
	int   PARAM_CIRCULANT;//1 to impose circulant constraints
	double  PARAM_TIME_LIMIT;
	int   PARAM_STRONGER_CUTS;//1 to use better RHS in the clique cuts
	int   PARAM_CPLEX;//1 to use CPLEX to separate clique cuts
	int   PARAM_MNTS;//set to 1 to use MNTS in the separation
	double	PARAM_TOUT_MNTS;//time limit for the execution of MNTS
	int   PARAM_NUM_RESTARTS_MNTS;//set to the number of restarts
	int   PARAM_NUM_ITERATIONS_MNTS;//set to the number of iterations
	int   PARAM_K_CUTS;//1 to insert Kalfleish inequalities
	int   PARAM_CLIQUE_JUMP_CUTS;
	int   PARAM_COVER_CUTS;
	int   PARAM_CUT_LOOP;
	int   AVOID_TRIANGLES;
	int   AVOID_QUADRANGLES;
	int   CHECK_SOLUTION;
	int   CUT_CALL_BACK_STRATEGY;
	//(0) --> CPX_USECUT_FORCE	The cut is added to the relaxation and stays there
	//(1) --> CPX_USECUT_PURGE	The cut is added to the relaxation but can be purged later on if CPLEX deems the cut ineffective.
	//(2) **ATTENTION IT DOED NOT WORK ANYMORE** --> CPX_USECUT_FILTER	The cut is treated exactly as cuts generated by CPLEX; that is, CPLEX applies its filtering process and may not even add the cut to the relaxation, for example, if CPLEX deems other cuts more effective, or if the cut is too dense.
	int   BRANCHING_STRATEGY;			//0-default, <N: 1--4 may have alternative meaning depending on the model, >4 random branching strategy>
	int   TREE_EXPLORATION_STRATEGY;
	//	0 CPX_NODESEL_DFS Depth-first search
	//1 CPX_NODESEL_BESTBOUND Best-bound search; default
	//2 CPX_NODESEL_BESTEST Best-estimate search
	//3 CPX_NODESEL_BESTEST_ALT Alternative best-estimate search
	int   HEURFREQ;
	//-1 None
	//0  Automatic: let CPLEX choose; default
	//Any positive integer  Apply the periodic heuristic at this frequency
	int CLIQUE_TARGET; //1 to use the TARGET PARAMETER FOR PABLO  AND CPLEX and 0 to let it compute a maximum clique (ATTENTION: even if the target is on Pablo can return a clique larger than the target)
	int CLIQUE_TARGET_RESIZE;//1 to reduce the Maximum clique to M or N and 0 to keep it as it is
	int MULTIPLE_CUTS;//>1 to add at most MULTIPLE_CUTS jump cuts for cliques of size m or n contained in a larger clique (with 0 it adds only one cut for the first smaller clique of size m or n)
	int RANDOM_SEED;//used to change the seed of CPLEX (it does not make a big difference in the instances that we have tested)
	int BRANCHING_VARIABLE_SELECTION;
	//	-1	CPX_VARSEL_MININFEAS	Branch on variable with minimum infeasibility
	//	//0	CPX_VARSEL_DEFAULT	Automatic: let CPLEX choose variable to branch on; default
	//	//1	CPX_VARSEL_MAXINFEAS	Branch on variable with maximum infeasibility
	//	//2	CPX_VARSEL_PSEUDO	Branch based on pseudo costs
	//	//3	CPX_VARSEL_STRONG	Strong branching
	//	//4	CPX_VARSEL_PSEUDOREDUCED	Branch based on pseudo reduced costs
	int NUMBER_OF_THREADS; //It determines the number of threads used by CPLEX (CPX_PARALLEL_DETERMINISTIC is set to have deterministic results)
	int  ID_TEST;						//id of the test
	int  LOAD_CUTS_FROM_FILE;			// 1: load cuts; 0: no cut-file I/O; -100: record unique supports and generating cliques (MODEL_3 only)
	int  MINIMIZE_CUTS;					//0 disabled; 1 heuristic minimization, repeated until a full pass removes nothing; 2 exact (MNTS+CliSAT) minimization, same repeat-until-fixpoint loop; 3 heuristic minimization like 1, but only a single pass (no repeat, regardless of outcome); 4 like 3, but on the high half of candidate distances only every other one is tried (stride 2), since the low half has a consistently ~1.4-1.5x higher empirical success rate; 5 like 4 but more concentrated: stride 2 on the low half too, high half skipped entirely (both scale with t via n_variable_MODEL_3, no fixed constant)
	////////////////////////////////////////////////////////////////////////////////

	/////////////////////////////////////CPLEX/////////////////////////////////////
	CPXENVptr env_clique,env_MODEL_1,env_MODEL_2,env_MODEL_3,env_MODEL_4;
	CPXLPptr lp_clique,lp_MODEL_1,lp_MODEL_2,lp_MODEL_3,lp_MODEL_4;
	int status,ccnt,rcnt,nzcnt,lpstat,nodecount,numrows,numcols;
	int* rmatbeg,*rmatind,*cmatbeg, *cmatind;
	double *rmatval,*cmatval,*rngval,*obj, *lb, *ub,*rhs,coef,objval,bestobjval;
	char *xctype,*sense;
	char **rowname,**colname;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int **LOOK_UP_RAMSEY;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	double *CLIQUE_SOL;
	double CLIQUE_VAL;
	double *CLIQUE_SOL_TEMP;
	double CLIQUE_VAL_TEMP;
	double magic_value;
	int *subset;
	int *data_subset;
	int cut_iter_counter;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	double *CLIQUE_BLUE;
	int size_CLIQUE_BLUE;
	double time_CLIQUE_BLUE;
	double *CLIQUE_RED;
	int size_CLIQUE_RED;
	double time_CLIQUE_RED;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	double *X_CALLBACK;
	double   cut_RHS;
	int    * cut_rmatind;
	double * cut_rmatval;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	double *X_CALLBACK_TEMP;
	int **edge_fixing_TEMP;
	////////////////////////////////////////////////////////////////////////////////


	////////////////////////////////////////////////////////////////////////////////
	int n_variable_MODEL_1;
	double *X_MODEL_1;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int n_variable_MODEL_2;
	double *X_MODEL_2;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int n_variable_MODEL_3;
	double *X_MODEL_3;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int n_variable_MODEL_4;
	double *X_MODEL_4;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int n_variable_MODEL_5;
	double *X_MODEL_5;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	double time_clique_BB;
	double time_clique_cplex;
	int  n_clique_calls_red;
	int  n_clique_calls_blue;
	int  n_cuts_red;
	int  n_cuts_blue;
	int  n_cuts_red_plus;
	int  n_cuts_blue_plus;
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	// Statistics for cut minimization procedure
	int  n_jumps_minimized_blue;   // Number of jumps removed from blue cliques
	int  n_jumps_minimized_red;    // Number of jumps added for red cliques (lifted)
	int  n_minimization_successes_blue;  // Number of times blue minimization changed at least one coefficient
	int  n_minimization_successes_red;   // Number of times red minimization changed at least one coefficient
	double time_minimization;       // Total time spent in minimization
	double time_minimization_rebuild;     // Diagnostic: time spent rebuilding edge_fixing_TEMP within minimization
	double time_minimization_cliquecheck; // Diagnostic: time spent in the per-candidate clique re-check within minimization
	long long sum_removed_jump_distance_red; // Diagnostic: sum of circular distances (jump_idx+1) of removed red jumps
	int min_removed_jump_distance_red;       // Diagnostic: smallest circular distance removed
	int max_removed_jump_distance_red;       // Diagnostic: largest circular distance removed
	long long n_jump_attempts_red;           // Diagnostic: total candidate-jump checks attempted (success + failure)
	long long n_jump_attempts_red_lowhalf;   // Diagnostic: attempts with distance <= n_variable_MODEL_3/2
	long long n_jump_attempts_red_highhalf;  // Diagnostic: attempts with distance > n_variable_MODEL_3/2
	long long n_jumps_minimized_red_lowhalf; // Diagnostic: successes with distance <= n_variable_MODEL_3/2
	long long n_jumps_minimized_red_highhalf;// Diagnostic: successes with distance > n_variable_MODEL_3/2
	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////////////////////
	int n_calls;
	int n_calls_heur;
	double time_MNTS;
	int n_CLISAT_successes;
	int n_MNTS_successes;
	int n_SimpleHeur_successes;
	int n_CLISAT_opt;
	////////////////////////////////////////////////////////////////////////////////


	////////////////////////////////////////////////////////////////////////////////
	bool SKIP_M_SEPARATION;
	bool SKIP_N_SEPARATION;
	////////////////////////////////////////////////////////////////////////////////

	int CLIQUE_JUMP_CUTS_M;
	int CLIQUE_JUMP_CUTS_N;
	int TRIANGLES_CUTS_M;
	int TRIANGLES_CUTS_N;
	int QUADRANGLES_CUTS_M;
	int QUADRANGLES_CUTS_N;

	////////////////////////////////////////////////////////////////////////////////
	// Structures for cuts read from files
	////////////////////////////////////////////////////////////////////////////////
	cut_data CUTS_M;      // blue cuts for PARAM_M
	cut_data CUTS_N;      // red cuts for PARAM_N
	set<vector<int> > RECORDED_CUTS_M; // unique blue supports written in recording mode
	set<vector<int> > RECORDED_CUTS_N; // unique red supports written in recording mode
	mutex RECORDED_CUTS_MUTEX;

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//BBS STUFF

	//choose one to the two options

	//using RamseySolver = Ramsey< copt::clique::CliSAT<bitgraph::ugraph, copt::clique::infoCliSAT, 128> >;	 //128 is the meaning of the universe
	//using RamseySolver = Ramsey< copt::clique::CliqueX<bitgraph::ugraph, copt::clique::infoCLQ<int>, 128> >;	 //128 is the meaning of
	using RamseySolver = Ramsey< copt::clique::CliqueX<bitgraph::ugraph, copt::clique::infoSAT, 128> >; 

	RamseySolver ci;

	int **edge_fixing;

	/***********************************************************************************/
	/*
	 * @brief: initializes the undirected graph
	 * @details: the last parameter of init() is the timeout for CliSAT (-1 means no timeout)
	 */
	void initialize_ug(int number_of_vertices)
	/***********************************************************************************/
	{

		clock_t time_start_creating=clock();

		//ci.init(number_of_vertices, PARAM_N, PARAM_M, -1 /* no timeout by default */);

		ci.init(number_of_vertices, PARAM_N, PARAM_M, PARAM_TIME_LIMIT);

		clock_t time_end_creating=clock();

	}


	/***********************************************************************************/
	void finalize_ug()
	/***********************************************************************************/
	{

		//nothing to do

	}


	/***********************************************************************************/
	/* @details: after run_edge(), global object ci is updated. Call A) ci.get_target_mode(), B) ci.get_time_mnts() C) ci.is_cert_opt() for the output, 	*																
	/* @output A) -1 UNKNOWN, 0 TARGET_NOT_FOUND, 1 TARGET_FOUND_SIMPLE_HEUR, 2 TARGET_FOUND_AMTS, 3 TARGET_FOUND_CliSAT
	/* 		   B) time in seconds 	
	/*		   C) true if optimality is certified
	/***********************************************************************************/

	int clique_solve_BB_edge_fixing
	(
			int** fixing,
			double* solution,
			bool circulant,
			int TARGET /* ramsey m or ramsey n */,
			bool flag_MNTS,
			double TOUT_MNTS,
			int MNTS_NUM_RESTARTS,
			int MNTS_NUM_ITERATIONS,
			bool color /* 0 for m and 1 for n  */
	)
	/***********************************************************************************/
	{

		ci.set_edges(fixing);

		// true or false to make the code write the graphs during the **exact separation** procedure

		auto r = ci.run_edge(circulant, flag_MNTS, TOUT_MNTS, TARGET, MNTS_NUM_RESTARTS, MNTS_NUM_ITERATIONS, true, ID_TEST, color);

		//ASSERT!
		if(r.w!=r.sol.size())
		{
			cout<<"w:"<<r.w<<"\t PROBLEM->sol_size:"<<r.sol.size()<<endl;

			for(int i=0;i<r.sol.size();i++)
			{
				cout << r.sol[i] << endl;
			}

			exit(-1);
		}

		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		//example to capture the internal state of CliSAT
		if (ci.is_time_out_clisat())
		{
			cout << "CLISAT timed out..." << endl;

			exit(-1);
		}
		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


		// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		// cout << "Info:"
		// 		<< "\t mode: "        << ci.get_target_mode()
		// 		<< "\t time_mnts: "   << ci.get_time_mnts()
		// 		<< "\t mnts_value: "   << ci.get_mnts_value()
		// 		<< "\t sol.size: "    << r.sol.size()
		// 		<< "\t TARGET: "      << TARGET
		// 		<< "\t is_cert_opt: " << ci.is_cert_opt()
		// 		<< "\t\t";

		// if (r.sol.size() >= TARGET) {
		// 	cout << "Cut found!" << endl;
		// } else {
		// 	cout << "Cut not found!" << endl;
		// }
		// cout << "Clique:\t";
		// for(int i=0;i<r.sol.size();i++)
		// {
		// 	cout << r.sol[i] << "\t";
		// }
		// cout << endl;
		// cin.get();
		// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		n_calls++;

		if(ci.get_target_mode()!=-1)
		{
			time_MNTS+=ci.get_time_mnts();

			if(ci.get_target_mode()==1)
			{
				n_SimpleHeur_successes++;
			}
			if(ci.get_target_mode()==2)
			{
				n_MNTS_successes++;
			}
			if(ci.get_target_mode()==3)
			{
				n_CLISAT_successes++;
			}
		}

		if(ci.is_cert_opt()==1)
		{
			n_CLISAT_opt++;
		}
		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



		for(int i=0;i<r.w;i++)
		{
			solution[r.sol[i]]=1;
		}

		return r.w;
	}

	/***********************************************************************************/
	int clique_solve_BB_edge_fixing_heur
	(
			int** fixing,
			double* solution,
			bool circulant,
			int TARGET /* ramsey m or ramsey n */,
			bool flag_MNTS,
			double TOUT_MNTS,
			int MNTS_NUM_RESTARTS,
			int MNTS_NUM_ITERATIONS,
			bool color /* 0 for m and 1 for n  */
	)
	/***********************************************************************************/
	{

		ci.set_edges(fixing);

		// true or false to make the code write the graphs during the **exact separation** procedure

		auto r = ci.run_edge_heur(circulant, flag_MNTS, TOUT_MNTS, TARGET, MNTS_NUM_RESTARTS, MNTS_NUM_ITERATIONS, false, ID_TEST, color);

		//ASSERT!
		if(r.w!=r.sol.size())
		{
			cout<<"w:"<<r.w<<"\t PROBLEM->sol_size:"<<r.sol.size()<<endl;

			for(int i=0;i<r.sol.size();i++)
			{
				cout << r.sol[i] << endl;
			}

			exit(-1);
		}

		n_calls_heur++;

		//		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		//
		//
		//		if(ci.get_target_mode()!=-1)
		//		{
		//			cout << "Heuristic target mode: " << ci.get_target_mode() << endl;
		//			cout << "size: " << r.w << " TARGET: " << TARGET << endl;
		//			//cin.get();
		//		}
		//		else
		//		{
		//			cout << "Heuristic target mode: UNKNOWN" << endl;
		//			//cin.get();
		//		}
		//		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		//
		//		/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		//		cout << "Info heur:"
		//				<< "\t mode: "        << ci.get_target_mode()
		//				<< "\t time_mnts: "   << ci.get_time_mnts()
		//				<< "\t mnts_value: "   << ci.get_mnts_value()
		//				<< "\t sol.size: "    << r.sol.size()
		//				<< "\t TARGET: "      << TARGET
		//				<< "\t is_cert_opt: " << ci.is_cert_opt()
		//				<< "\t\t";
		//
		//		if (r.sol.size() >= TARGET) {
		//			cout << "Lifting!" << endl;
		//		} else {
		//			cout << "No Lifting!" << endl;
		//		}
		//		cout << "Clique:\t";
		//		for(int i=0;i<r.sol.size();i++)
		//		{
		//			cout << r.sol[i] << "\t";
		//		}
		//		cout << endl;
		//		//cin.get();
		//		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


		for(int i=0;i<r.w;i++)
		{
			solution[r.sol[i]]=1;
		}

		return r.w;
	}



	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



	///////////////////////////////////////////////////////////////////////////////////
	// Partial-colouring propagator (MODEL_3 only, active iff PARAM_OPTIONS==1) 2026-09-02
	// Counters + scratch arrays; inert (zeroed/allocated but unused) when the flag is off.
	long long pp_calls;              // branch-callback invocations
	long long pp_prunes_blue;        // nodes fathomed: forced blue K_M in the fixed part
	long long pp_prunes_red;         // nodes fathomed: forced red  K_N in the fixed part
	long long pp_fixed_sum;          // sum over prunes of #locally-fixed distance variables
	long long pp_depth_sum;          // sum over prunes of the CPLEX node depth
	int       pp_max_fixed_at_prune; // max #fixed distance variables seen at a prune
	double    time_propagator;       // total seconds spent inside the propagator callback
	double   *pp_lb;                 // scratch: node local lower bounds (n_variable_MODEL_3)
	double   *pp_ub;                 // scratch: node local upper bounds
	// PARAM_OPTIONS==3 adds a complete bitset pre-check on integral candidates in the lazy
	// callback, replacing the max-clique separator there (CLIQUE_TARGET==1, MINIMIZE_CUTS==0):
	long long pp_fast_calls;         // integral candidates screened by the fast test
	long long pp_fast_hits_blue;     // blue K_M found by the fast test (cut built from it)
	long long pp_fast_hits_red;      // red  K_N found by the fast test

} data;



#endif
